linkedin:
  keywords:
    - "python"
    - "junior"
  location: "remote"
  max_results: 100

proxy:
  enabled: false
  urls: []

rate_limit:
  requests_per_second: 0.5
  burst: 1

filters:
  include_keywords:
    - "golang"
    - "go backend"
  exclude_keywords:
    - "senior"
    - "pleno"
  exclude_companies: []
  include_companies: []
  include_locations: []
  exclude_locations: []
  min_description_lengh: 10000
telegram:
  bot_token: // "SEU BOT TOKEN AQUI ENTRE ASPAS"
  chat_id: // SEU CHAT ID AQUI